### ISSUE TITLE
poy 5.1.1 crashes when given a non-command string that ends with '()'

### ISSUE THREAD

**Issue by jdl1685** [amnh/poy5#1]
Here's how to reproduce it. First an example of how POY correctly detects a faulty command when the faulty commandname does not end with '()', then an example of a Fatal Errot when that same commandname ends with '()'.

 $ poy
Information : Welcome to POY 5.1.1 (5.1.1)
Compiled on Mon Nov 17 18:47:49 CET 2014 with parallel off, interface
readline, likelihood off, and concorde off.
Copyright (C) 2011, 2012, 2013, 2014 Andres Varon, Nicholas Lucaroni, Lin
Hong, Ward Wheeler, and the American Museum of Natural History.
POY 5.1.1 comes with ABSOLUTELY NO WARRANTY; This is free software, and you
are welcome to redistribute it under the GNU General Public License Version
2, June 1991.

Information : Setting random seed value to -720489789
Information : 
Information : 
Information : 
Information : For help, type help().

```
          Enjoy!
```

Information : 
                Trees:
                  Storing 0 trees 
                Cost Mode: Normal Direct Optimization
poy> thisisnotacomand
Error : Command error between characters 0 and 16:
            [left_parenthesis] expected after LIDENT _ (in [plugin])

poy> thisisnotacommand()
Error : There is no command thisisnotacommand
Fatal error: exception Failure("Illegal command thisisnotacommand")

**Comment by nrlucaroni** [comment]
Sorry I missed this issue being submitted here. I'll have to enable email messaging for things like this.

I doubled checked this issue with the head of this repo and things worked fine. You've described the behavior of `debug_pass_errors` flag in `poy.ml` being set to `true`. I believe we released the codebase with that included, but has been removed.

My apologies for the confusion.
